### ISSUE TITLE
Win Python 3.6 issue

### ISSUE THREAD

**Issue by shahidkarimi** [weskerfoot/DeleteFB#83] opened 2019-08-18 14:02 UTC
DevTools listening on ws://127.0.0.1:62848/devtools/browser/0160fa76-3a51-4e69-9d7f-e6b49f335924
Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\win8.1\AppData\roaming\Python\Python36\scripts\deletefb.exe\__main__.py", line 9, in <module>
  File "C:\Users\win8.1\AppData\Roaming\Python\Python36\site-packages\deletefb\deletefb.py", line 58, in run_delete
    is_headless=args.is_headless
  File "C:\Users\win8.1\AppData\Roaming\Python\Python36\site-packages\deletefb\deletefb.py", line 81, in delete_posts

**Comment by weskerfoot** [comment] 2019-08-19 03:50
Could you give more detail about what happens when you hit that exception? Was it unable to delete the posts? I assume you got it running and it logged in, but something caused an exception while trying to delete a post.

**Comment by weskerfoot** [comment] 2019-09-14 23:16
Closing since it's been almost a month and I cannot reproduce windows issues

**Closed by weskerfoot** 2019-09-14 23:16 UTC
Labels: question
