### ISSUE TITLE
Support deleting all comments

### ISSUE THREAD

**Issue by sgama** [weskerfoot/DeleteFB#27] opened 2019-05-23 19:22 UTC
This issue builds on top of #21 ,

I would like to be able to delete all my comments. There was a Chrome extension in the past called [Social Book Post Manager](https://chrome.google.com/webstore/detail/social-book-post-manager/ljfidlkcmdmmibngdfikhffffdmphjae), but it does not seem to work anymore.

Based on a very short investigation, the following steps may work:

- Navigate to [https://www.facebook.com/USERNAME/allactivity?privacy_source=activity_log&category_key=commentscluster](https://www.facebook.com/USERNAME/allactivity?privacy_source=activity_log&category_key=commentscluster)
- Look for all lists that have the class `uiList _4kg`: `<ul class="uiList _4kg"...`
- Navigate a few divs down until you find the `Delete` node and click
- Repeat until there are no more lists with class `uiList _4kg` at which point, refresh the page

**Comment by weskerfoot** [comment] 2019-05-23 20:04
Thanks, I think we can probably use a similar approach for https://github.com/weskerfoot/DeleteFB/issues/21

**Comment by weskerfoot** [comment] 2019-06-09 01:20
This depends on having https://github.com/weskerfoot/DeleteFB/issues/55 implemented

**Comment by weskerfoot** [comment] 2019-06-16 06:30
Closing since it's a duplicate of https://github.com/weskerfoot/DeleteFB/issues/45

**Closed by weskerfoot** 2019-06-16 06:30 UTC
Labels: enhancement
