### ISSUE TITLE
ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.8/typing.py)

### ISSUE THREAD

**Issue by tabekooi** [weskerfoot/DeleteFB#96] opened 2019-12-12 17:49 UTC
I have been using the script for a while now. Suddenly this happened:

deletefb  --headless -E 'EDITTED@gmail.com' -P 'EDITTED' -U 'https://www.facebook.com/EDITTED
'
Traceback (most recent call last):
  File "/home/tabe/.local/bin/deletefb", line 11, in <module>
    load_entry_point('delete-facebook-posts==1.1.10', 'console_scripts', 'deletefb')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tabe/.local/lib/python3.8/site-packages/deletefb/deletefb.py", line 4, in <module>
    from .tools.likes import unlike_pages
  File "/home/tabe/.local/lib/python3.8/site-packages/deletefb/tools/likes.py", line 1, in <module>
    from .archive import archiver
  File "/home/tabe/.local/lib/python3.8/site-packages/deletefb/tools/archive.py", line 8, in <module>
    import cattr
  File "/home/tabe/.local/lib/python3.8/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/home/tabe/.local/lib/python3.8/site-packages/cattr/converters.py", line 3, in <module>
    from ._compat import (
  File "/home/tabe/.local/lib/python3.8/site-packages/cattr/_compat.py", line 86, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.8/typing.py)

maybe my linux (manajaro) updated python.

any solution?

**Comment by tabekooi** [comment] 2019-12-12 18:06
updating just gives that all requirements already are satisfied.

**Comment by weskerfoot** [comment] 2019-12-12 23:39
@tabekooi it's a known issue with python 3.8 I'm afraid. You can install 3.7 with pyenv. There is an open issue for it with the `cattrs` library (which is where the issue is).

You can see here that there is a fix but it hasn't been released https://github.com/Tinche/cattrs/pull/73

Installing an older version (3.7 works for me) using pyenv will make it work until it gets a proper fix.

**Comment by weskerfoot** [comment] 2019-12-12 23:40
Let me know if you need help getting it to work with pyenv. I'm going to update the docs or perhaps you could try running the docker version of it?

**Comment by tabekooi** [comment] 2019-12-12 23:41
Thank you for your usefull comment.
Kind regards.

**Comment by weskerfoot** [comment] 2019-12-12 23:46
Looks like it might be possible to use this instead https://pypi.org/project/cattrs-3.8/

I'm going to try and re-build and see if it solves the issue.

**Comment by weskerfoot** [comment] 2019-12-13 03:57
@tabekooi Please give the latest commit a try. I've merged (hopefully) a fix.

**Closed** 2019-12-13 03:57 UTC
Labels: bug

**Comment by weskerfoot** [comment] 2019-12-13 04:09
I've pushed a new version that fixes it

**Comment by tabekooi** [comment] 2019-12-13 08:28
Thank you!

**Comment by privacyguy123** [comment] 2020-12-06 13:45
So use 3.7 or 3.7.7?

**Comment by pawelniewie** [comment] 2021-01-05 09:50
I'm still having this issue with repo at `a5ed694`.

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/pawel/Development/DeleteFB/deletefb/deletefb.py", line 4, in <module>
    from .tools.likes import unlike_pages
  File "/Users/pawel/Development/DeleteFB/deletefb/tools/likes.py", line 1, in <module>
    from .archive import archiver
  File "/Users/pawel/Development/DeleteFB/deletefb/tools/archive.py", line 8, in <module>
    import cattr
  File "/Users/pawel/Library/Python/3.9/lib/python/site-packages/cattr/__init__.py", line 2, in <module>
    from .converters import Converter, UnstructureStrategy
  File "/Users/pawel/Library/Python/3.9/lib/python/site-packages/cattr/converters.py", line 15, in <module>
    from ._compat import (
  File "/Users/pawel/Library/Python/3.9/lib/python/site-packages/cattr/_compat.py", line 87, in <module>
    from typing import _Union
ImportError: cannot import name '_Union' from 'typing' (/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py)
```

```
python3 --version                                                                                                                                     on master|…
Python 3.9.1
```

**Comment by AlexKalopsia** [comment] 2021-03-01 16:31
Also having this issue, I am on python 3.9.0
