### ISSUE TITLE
Stuck on post where neither "deleting" nor "hiding" was an option

### ISSUE THREAD

**Issue by Neugierdsnase** [weskerfoot/DeleteFB#22] opened 2019-05-22 18:03 UTC
Maybe related to #17. The program seems to have been stuck on a post from 2013 where neither "deleting" nor "hiding" was an option. I manually "untagged" me from the post/photo and restarted the program, which worked fine, but this might want to be considered fixing as a future enhancement.

**Comment by Neugierdsnase** [comment] 2019-05-22 19:59
I'm going to close this again, since I am not sure anymore this is what actually happened and I might have jumped the gun here.

**Comment by weskerfoot** [comment] 2019-05-22 23:00
I think this is a real thing, but it's hard to reproduce. I think Facebook has removed certain features over the years so things are a bit inconsistent.

**Comment by weskerfoot** [comment] 2019-05-26 21:56
Reopening since I think it might be a real issue but it's hard to reproduce.

**Comment by jsmbennett** [comment] 2019-05-27 18:02
I'm consistently stuck on this step, and the situation is this:

A friend posted a picture on another friends' wall in which I was tagged. The option presented in the context menu is to "Remove Tag".

![Screenshot from 2019-05-27 11-01-48](https://user-images.githubusercontent.com/2488162/58434126-f8c61600-806e-11e9-8e94-4231d9e9d19f.png)

**Comment by jsmbennett** [comment] 2019-05-27 18:05
Found another post with it: the parameter for selenium is:

`data-feed-option-name="UNTAG"`

**Comment by weskerfoot** [comment] 2019-05-27 19:00
Thanks, I think I can add that, even if I can't test it

**Comment by weskerfoot** [comment] 2019-05-27 19:08
It should just need an additional case here to handle it https://github.com/weskerfoot/DeleteFB/blob/565e01f6d0499f2b405ef50c006d772068e253fe/deletefb/tools/wall.py#L27

**Comment by weskerfoot** [comment] 2019-05-30 15:07
https://github.com/weskerfoot/DeleteFB/pull/44 may solve this

Could someone test? @jsmbennett @Neugierdsnase

**Comment by weskerfoot** [comment] 2019-06-02 20:48
Should be fixed now

**Closed by weskerfoot** 2019-06-02 20:48 UTC
Labels: bug
