### ISSUE TITLE
try to make it ignore the tagged posts

### ISSUE THREAD

**Issue by skerrepy** [weskerfoot/DeleteFB#43] opened 2019-05-30 01:11 UTC
sometimes i get an issue the bot gets stuck with the posts that my friend tagged me in

**Comment by weskerfoot** [comment] 2019-05-30 01:51
Thanks, I think this is a duplicate of https://github.com/weskerfoot/DeleteFB/issues/22

It should be fixed relatively soon, thanks for filing an issue!

**Closed by weskerfoot** 2019-05-30 01:51 UTC
Labels: duplicate
